/**
 * Generates clean, native LaTeX TikZ code for the Shor [[9, 1, 3]] code lattice.
 * Conforms to Crumble RGB = XYZ standard (Red = X, Green = Y, Blue = Z).
 * Can be compiled standalone or pasted directly into academic papers.
 */

import { createDiagramMetadata } from './metadata';

export interface ShorTikzOptions {
  standalone?: boolean;
  asFigure?: boolean; // Wrap in \begin{figure}[htbp] ... \end{figure} (default: true if not standalone)
  caption?: string;   // LaTeX figure caption
  label?: string;     // LaTeX figure label (default: 'fig:shor-code')
  paperMode?: boolean; // Light / white paper styling (default: true for LaTeX)
  activeCorrection?: { qubit: number; pauli: number } | null;
}

function buildDefaultCaption(errors: Uint8Array | number[], syndromes: Uint8Array | number[]): string {
  const errorNames = ['I', 'X', 'Y', 'Z'];
  const activeErrors: string[] = [];
  for (let i = 0; i < errors.length; i++) {
    const p = errors[i];
    if (p !== 0) {
      activeErrors.push(`$${errorNames[p]}$ on $Q_{${i}}$`);
    }
  }

  const activeDefects: string[] = [];
  for (let s = 0; s < syndromes.length; s++) {
    if (syndromes[s] === 1) {
      activeDefects.push(`$S_{${s + 1}}$`);
    }
  }

  let desc = 'Shor $[[9, 1, 3]]$ quantum error-correcting code lattice state';
  if (activeErrors.length === 0) {
    desc += ' in the ground code space (zero defects).';
  } else {
    desc += ` with active Pauli error${activeErrors.length > 1 ? 's' : ''} (${activeErrors.join(', ')})`;
    if (activeDefects.length > 0) {
      desc += ` triggering syndrome defect${activeDefects.length > 1 ? 's' : ''} ${activeDefects.join(', ')}.`;
    } else {
      desc += ' producing no syndrome defects.';
    }
  }
  desc += ' Color standard follows Crumble (Red $= X$, Green $= Y$, Blue $= Z$).';
  return desc;
}

export function generateShorTikz(
  errors: Uint8Array | number[],
  syndromes: Uint8Array | number[],
  options: ShorTikzOptions = {},
): string {
  const {
    standalone = false,
    asFigure = !options.standalone, // Default to true if not standalone
    caption,
    label = 'fig:shor-code',
    paperMode = true,
    activeCorrection = null,
  } = options;

  const metadata = createDiagramMetadata('shor', errors, syndromes);

  const getPauliColorName = (p: number): { fill: string; draw: string; text: string; label: string } => {
    switch (p) {
      case 1:
        return { fill: 'red!80!black', draw: 'red!60!black', text: 'white', label: 'X' };
      case 2:
        return { fill: 'green!60!black', draw: 'green!50!black', text: 'white', label: 'Y' };
      case 3:
        return { fill: 'blue!80!black', draw: 'blue!60!black', text: 'white', label: 'Z' };
      default:
        return paperMode
          ? { fill: 'gray!15', draw: 'gray!60', text: 'black', label: 'I' }
          : { fill: 'slate900', draw: 'slate700', text: 'white', label: 'I' };
    }
  };

  const lines: string[] = [];

  // 1. Embedded learn-qec state comment for lossless round-trip re-importing
  lines.push(`% learn-qec-state: ${JSON.stringify(metadata)}`);
  lines.push('% ==========================================');
  lines.push('% Shor [[9, 1, 3]] Quantum Error Correction Code');
  lines.push('% Generated by learn-qec (https://alban.github.io/learn-qec/)');
  lines.push('% RGB = XYZ Color Standard: Red = X, Green = Y, Blue = Z');
  lines.push('% ==========================================');
  lines.push('');

  if (standalone) {
    lines.push('\\documentclass[tikz,border=8pt]{standalone}');
    lines.push('\\usepackage{amsmath,amssymb}');
    lines.push('\\usetikzlibrary{calc,positioning,shapes.geometric}');
    lines.push('\\begin{document}');
    lines.push('');
  } else if (asFigure) {
    lines.push('\\begin{figure}[htbp]');
    lines.push('  \\centering');
  }

  const indent = (!standalone && asFigure) ? '  ' : '';

  lines.push(`${indent}\\begin{tikzpicture}[`);
  lines.push(`${indent}  scale=1.1,`);
  lines.push(`${indent}  every node/.style={transform shape},`);
  lines.push(`${indent}  qubit/.style={circle, draw, minimum size=1.1cm, font=\\bfseries\\small, inner sep=0pt},`);
  lines.push(`${indent}  zcheck/.style={circle, draw, minimum size=0.6cm, font=\\sffamily\\scriptsize, inner sep=0pt},`);
  lines.push(`${indent}  blockCard/.style={draw=gray!50, rounded corners=8pt, dashed, thick}`);
  lines.push(`${indent}]`);
  lines.push('');

  // Define colors
  lines.push('  % Palette definitions');
  lines.push('  \\definecolor{qecRed}{RGB}{220, 38, 38}');
  lines.push('  \\definecolor{qecGreen}{RGB}{5, 150, 105}');
  lines.push('  \\definecolor{qecBlue}{RGB}{37, 99, 235}');
  lines.push('  \\definecolor{targetGold}{RGB}{245, 158, 11}');
  lines.push('');

  // 3 Block Cards: Boundaries in Y = -0.90 .. 5.90
  const blockX = [0.0, 3.8, 7.6];
  for (let b = 0; b < 3; b++) {
    const x = blockX[b];
    lines.push(`  % --- Block ${b} ---`);
    lines.push(
      `  \\draw[blockCard, fill=${paperMode ? 'gray!5' : 'black!20'}] (${(x - 1.25).toFixed(2)}, -0.90) rectangle (${(x + 1.25).toFixed(2)}, 5.90);`,
    );
    // Header positioned at Y = 5.50 (completely clear of Q0 top edge at Y = 4.90)
    lines.push(
      `  \\node[font=\\sffamily\\bfseries\\footnotesize, text=gray!70] at (${x.toFixed(2)}, 5.50) {BLOCK ${b}};`,
    );
    lines.push('');
  }

  // Bit-flip connecting lines (Z-checks)
  lines.push('  % Bit-flip check lines');
  const zChecks = [
    { id: 0, qA: 0, qB: 1, x: blockX[0], y: 3.3, label: 'S_1' },
    { id: 1, qA: 1, qB: 2, x: blockX[0], y: 1.1, label: 'S_2' },
    { id: 2, qA: 3, qB: 4, x: blockX[1], y: 3.3, label: 'S_3' },
    { id: 3, qA: 4, qB: 5, x: blockX[1], y: 1.1, label: 'S_4' },
    { id: 4, qA: 6, qB: 7, x: blockX[2], y: 3.3, label: 'S_5' },
    { id: 5, qA: 7, qB: 8, x: blockX[2], y: 1.1, label: 'S_6' },
  ];

  zChecks.forEach((zc) => {
    const isDefect = (syndromes[zc.id] || 0) === 1;
    const style = isDefect
      ? 'thick, draw=qecBlue'
      : 'densely dashed, draw=gray!40';
    // Draw vertical connection lines between qubits
    if (zc.id % 2 === 0) {
      lines.push(`  \\draw[${style}] (${zc.x.toFixed(2)}, 4.40) -- (${zc.x.toFixed(2)}, 2.20);`);
    } else {
      lines.push(`  \\draw[${style}] (${zc.x.toFixed(2)}, 2.20) -- (${zc.x.toFixed(2)}, 0.00);`);
    }
  });
  lines.push('');

  // Z-check nodes
  lines.push('  % Z-check stabilizer nodes');
  zChecks.forEach((zc) => {
    const isDefect = (syndromes[zc.id] || 0) === 1;
    const fill = isDefect
      ? 'fill=qecBlue, text=white, draw=qecBlue!80'
      : 'fill=white, text=gray!80, draw=gray!50';
    lines.push(`  \\node[zcheck, ${fill}] (zc${zc.id}) at (${zc.x.toFixed(2)}, ${zc.y.toFixed(2)}) {$${zc.label}$};`);
  });
  lines.push('');

  // 9 Data Qubits: Qtop = 4.40, Qmid = 2.20, Qbot = 0.00
  lines.push('  % Data Qubits (Q0..Q8)');
  const qubitCoords: { [key: number]: { x: number; y: number } } = {
    0: { x: blockX[0], y: 4.40 },
    1: { x: blockX[0], y: 2.20 },
    2: { x: blockX[0], y: 0.00 },
    3: { x: blockX[1], y: 4.40 },
    4: { x: blockX[1], y: 2.20 },
    5: { x: blockX[1], y: 0.00 },
    6: { x: blockX[2], y: 4.40 },
    7: { x: blockX[2], y: 2.20 },
    8: { x: blockX[2], y: 0.00 },
  };

  for (let q = 0; q < 9; q++) {
    const coord = qubitCoords[q];
    const pauli = errors[q] || 0;
    const style = getPauliColorName(pauli);
    const isTarget = activeCorrection?.qubit === q;

    if (isTarget) {
      lines.push(`  \\draw[very thick, dashed, draw=targetGold] (${coord.x.toFixed(2)}, ${coord.y.toFixed(2)}) circle (0.68cm);`);
    }

    const nodeLabel = pauli !== 0 ? `$\\mathbf{${style.label}}$` : `$Q_${q}$`;
    lines.push(
      `  \\node[qubit, fill=${style.fill}, draw=${style.draw}, text=${style.text}] (q${q}) at (${coord.x.toFixed(2)}, ${coord.y.toFixed(2)}) {${nodeLabel}};`,
    );
  }
  lines.push('');

  // Phase-flip check brackets (S7 at top Y=5.90..6.60, S8 at bottom Y=-0.90..-1.60)
  lines.push('  % Phase-flip checks (S7, S8 brackets)');
  const s7Defect = (syndromes[6] || 0) === 1;
  const s7Style = s7Defect ? 'very thick, draw=qecRed' : 'thick, draw=gray!60';
  const s7BadgeFill = s7Defect ? 'fill=qecRed, text=white' : 'fill=white, text=gray!80, draw=gray!40';
  lines.push(`  \\draw[${s7Style}] (${blockX[0].toFixed(2)}, 5.90) -- (${blockX[0].toFixed(2)}, 6.60) -- (${blockX[1].toFixed(2)}, 6.60) -- (${blockX[1].toFixed(2)}, 5.90);`);
  lines.push(`  \\node[draw, rounded corners=4pt, font=\\scriptsize\\bfseries, ${s7BadgeFill}] at (${((blockX[0] + blockX[1]) / 2).toFixed(2)}, 6.60) {$S_7: \\text{Phase}(0 \\leftrightarrow 1)$};`);
  lines.push('');

  const s8Defect = (syndromes[7] || 0) === 1;
  const s8Style = s8Defect ? 'very thick, draw=qecRed' : 'thick, draw=gray!60';
  const s8BadgeFill = s8Defect ? 'fill=qecRed, text=white' : 'fill=white, text=gray!80, draw=gray!40';
  lines.push(`  \\draw[${s8Style}] (${blockX[1].toFixed(2)}, -0.90) -- (${blockX[1].toFixed(2)}, -1.60) -- (${blockX[2].toFixed(2)}, -1.60) -- (${blockX[2].toFixed(2)}, -0.90);`);
  lines.push(`  \\node[draw, rounded corners=4pt, font=\\scriptsize\\bfseries, ${s8BadgeFill}] at (${((blockX[1] + blockX[2]) / 2).toFixed(2)}, -1.60) {$S_8: \\text{Phase}(1 \\leftrightarrow 2)$};`);
  lines.push('');

  lines.push(`${indent}\\end{tikzpicture}`);

  if (standalone) {
    lines.push('\\end{document}');
  } else if (asFigure) {
    const figureCaption = caption || buildDefaultCaption(errors, syndromes);
    lines.push(`  \\caption{${figureCaption}}`);
    lines.push(`  \\label{${label}}`);
    lines.push('\\end{figure}');
  }

  return lines.join('\n');
}
